### PR TITLE
New chainlink version and address changed to payable.

### PR DESCRIPTION
**Pull request by emrahsariboz**

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
I didn't do this in the video, and it's not needed in version 0.6.6 of the video, but it might be good to include in a comment for 0.8.7.

Could you make this a comment?

**Comment by PatrickAlphaC** [comment]
Also, I think we should stick with 0.6 for this file, since that'll match what we did in the video.

**Comment by emrahsariboz** [comment]
Sure, I just changed the code back to the original and added the comment for users who use a newer version of chainlink contracts.

**Comment by PatrickAlphaC** [comment]
Thank you!

**Pull request merged**
